
trigger:
  - master

resources:
  - repo: self

variables:
  artifactName: 'tvmazeapp'

stages:
  - stage: CICD
    displayName: Build and Deploy
    jobs:
      - job: CICD
        displayName: Build & Deploy
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
          - script: |
              npm install
            displayName: 'npm install'
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Run test cases'
          - script: |
              npm run test
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
          - script: |
              npm run build
            displayName: 'npm build package'
          - task: CopyFiles@2
            inputs:
              contents: 'dist/**'
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: AzureFileCopy@4
            inputs:
              SourcePath: 'dist/**'
              azureSubscription: 'Pay-As-You-Go (331a493d-9fb2-4ba8-9852-0fa43ef4fa76)'
              Destination: 'AzureBlob'
              storage: 'tvmaze'
              ContainerName: '$web'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)
              artifactName: $(artifactName)